@startuml
   title Customer
   participant "Customer" as cus
   participant "Shopping Cart" as sc
   participant "Product" as p
   participant "Order" as order
   participant "Payment" as pm
   cus->p: Search product list
   cus->sc: Checkout product
   sc->order: Create new order
   loop Add products
        activate order
        sc -> order: Add products
        sc -> order: Remove products
        order --> sc: products total
        deactivate order
   end
   sc->order: Calculate
   sc->order: Finalize sale
   activate order
   order --> cus: Total
   deactivate order

   cus->order: Submit payment
   order->pm: Create payment
   pm-->cus: Results

@enduml
