@startuml
    title Shop
    skinparam participantPadding 140
    actor "Shop" as shop
    participant "Profile" as r
    participant "Product" as p
    participant "Bank" as b
    
    shop->r: Onboarding to system
    r->shop: Create profile success
    
    shop->p: Manage Product
    activate p
    loop Manage products in shop
            shop->p: Search Product
        activate p
            p->shop: 
        deactivate p
            shop->p: Add Product
        activate p
            p->shop: 
        deactivate p
            shop->p: Edit Product
        activate p
            p->shop: 
        deactivate p
            shop->p: Delete Product
        activate p
            p->shop: 
        deactivate p
    end

    p->shop: Results
    deactivate p

    shop->r: Inquire balance
    r->b:
    activate b
    b->r:
    deactivate b
    r->shop: Results
    
    shop->r: Check report
    r->b:
    activate b
    b->r:
    deactivate b
    r->shop: Results
@enduml
